package com.shecancode.order.controller;
import com.shecancode.order.client.*; import com.shecancode.order.dto.OrderDtos.*; import com.shecancode.order.model.*; import com.shecancode.order.repo.*; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import java.math.*; import java.time.*; import java.time.format.*; import java.util.*;
@RestController @RequestMapping("/api/orders") public class OrderController {
 private final CartRepository carts;private final CartItemRepository items;private final OrderRepository orders;private final OrderItemRepository orderItems;private final ProductClient products;private final UserClient users;private final NotificationClient notifications;
 public OrderController(CartRepository c,CartItemRepository i,OrderRepository o,OrderItemRepository oi,ProductClient p,UserClient u,NotificationClient n){carts=c;items=i;orders=o;orderItems=oi;products=p;users=u;notifications=n;}
 private Cart cart(Long userId){return carts.findByUserId(userId).orElseGet(()->{Cart c=new Cart();c.setUserId(userId);return carts.save(c);});}
 @GetMapping("/cart/{userId}") public List<CartItem> cartItems(@PathVariable Long userId){return items.findByCartId(cart(userId).getId());}
 @PostMapping("/cart/{userId}/items") public List<CartItem> add(@PathVariable Long userId,@RequestBody CartRequest r){ProductClient.ProductView p=products.get(r.productId());if(!p.active()||p.stockQuantity()<r.quantity())throw new IllegalArgumentException("Insufficient stock");Cart c=cart(userId);CartItem i=items.findByCartIdAndProductId(c.getId(),p.id()).orElseGet(CartItem::new);i.setCartId(c.getId());i.setProductId(p.id());i.setProductName(p.name());i.setUnitPrice(p.price());i.setQuantity((i.getId()==null?0:i.getQuantity())+r.quantity());i.setSubtotal(p.price().multiply(BigDecimal.valueOf(i.getQuantity())));items.save(i);return items.findByCartId(c.getId());}
 @PutMapping("/cart/{userId}/items/{itemId}") public List<CartItem> update(@PathVariable Long userId,@PathVariable Long itemId,@RequestBody CartRequest r){Cart c=cart(userId);CartItem i=items.findById(itemId).orElseThrow();if(!i.getCartId().equals(c.getId()))throw new IllegalArgumentException("Wrong cart");ProductClient.ProductView p=products.get(i.getProductId());if(r.quantity()<1||p.stockQuantity()<r.quantity())throw new IllegalArgumentException("Invalid quantity");i.setQuantity(r.quantity());i.setUnitPrice(p.price());i.setSubtotal(p.price().multiply(BigDecimal.valueOf(r.quantity())));items.save(i);return items.findByCartId(c.getId());}
 @DeleteMapping("/cart/{userId}/items/{itemId}") public List<CartItem> remove(@PathVariable Long userId,@PathVariable Long itemId){Cart c=cart(userId);CartItem i=items.findById(itemId).orElseThrow();if(!i.getCartId().equals(c.getId()))throw new IllegalArgumentException("Wrong cart");items.delete(i);return items.findByCartId(c.getId());}
 @DeleteMapping("/cart/{userId}") @Transactional public void clear(@PathVariable Long userId){items.deleteByCartId(cart(userId).getId());}
 @PostMapping("/checkout") @Transactional public CustomerOrder checkout(@RequestBody CheckoutRequest r){UserClient.UserView u=users.get(r.userId());if(!u.enabled())throw new IllegalArgumentException("User disabled");UserClient.AddressView a=users.address(r.userId(),r.addressId());Cart c=cart(r.userId());List<CartItem> ci=items.findByCartId(c.getId());if(ci.isEmpty())throw new IllegalArgumentException("Cart is empty");List<CartItem> reserved=new ArrayList<>();try{BigDecimal total=BigDecimal.ZERO;for(CartItem i:ci){ProductClient.ProductView p=products.get(i.getProductId());products.reduce(p.id(),new ProductClient.StockRequest(i.getQuantity()));reserved.add(i);i.setUnitPrice(p.price());i.setSubtotal(p.price().multiply(BigDecimal.valueOf(i.getQuantity())));total=total.add(i.getSubtotal());}CustomerOrder o=new CustomerOrder();o.setOrderNumber("ORD-"+LocalDate.now().format(DateTimeFormatter.BASIC_ISO_DATE)+"-"+System.currentTimeMillis()%1000000);o.setUserId(r.userId());o.setTotalAmount(total);o.setDeliveryAddress(String.join(", ",a.province(),a.district(),a.sector(),a.street()==null?"":a.street()));o=orders.save(o);for(CartItem i:ci){OrderItem x=new OrderItem();x.setOrderId(o.getId());x.setProductId(i.getProductId());x.setProductName(i.getProductName());x.setUnitPrice(i.getUnitPrice());x.setQuantity(i.getQuantity());x.setSubtotal(i.getSubtotal());orderItems.save(x);}items.deleteByCartId(c.getId());try{notifications.create(new NotificationClient.NotificationRequest(r.userId(),"Order Created","Your order "+o.getOrderNumber()+" was created."));}catch(Exception ignored){}return o;}catch(RuntimeException e){for(CartItem i:reserved)try{products.restore(i.getProductId(),new ProductClient.StockRequest(i.getQuantity()));}catch(Exception ignored){}throw e;}}
 @GetMapping("/user/{userId}") public List<CustomerOrder> userOrders(@PathVariable Long userId){return orders.findByUserIdOrderByCreatedAtDesc(userId);}
 @GetMapping("/{id}") public Map<String,Object> one(@PathVariable Long id){CustomerOrder o=orders.findById(id).orElseThrow();return Map.of("order",o,"items",orderItems.findByOrderId(id));}
 @PatchMapping("/{id}/cancel") public CustomerOrder cancel(@PathVariable Long id){CustomerOrder o=orders.findById(id).orElseThrow();if(!(o.getStatus().equals("PENDING")||o.getStatus().equals("CONFIRMED")))throw new IllegalArgumentException("Cannot cancel");for(OrderItem i:orderItems.findByOrderId(id))products.restore(i.getProductId(),new ProductClient.StockRequest(i.getQuantity()));o.setStatus("CANCELLED");orders.save(o);try{notifications.create(new NotificationClient.NotificationRequest(o.getUserId(),"Order Cancelled","Order "+o.getOrderNumber()+" was cancelled."));}catch(Exception ignored){}return o;}
 @PatchMapping("/{id}/status") public CustomerOrder status(@PathVariable Long id,@RequestBody StatusRequest r){CustomerOrder o=orders.findById(id).orElseThrow();o.setStatus(r.status());orders.save(o);try{notifications.create(new NotificationClient.NotificationRequest(o.getUserId(),"Order Updated","Order "+o.getOrderNumber()+" is now "+r.status()+"."));}catch(Exception ignored){}return o;}
 @GetMapping public List<CustomerOrder> all(){return orders.findAll();}
}
